services:

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/src
    ports:
      - 8080:80
    depends_on:
      - laravel
    networks:
      - dev_network

  laravel:
    container_name: laravel
    build:
      context: ./docker/php
    volumes:
      - ./:/src
      - /src/node_modules
      - vendor:/src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log
    depends_on:
      - db
    networks:
      - dev_network

  # MySQL
  db:
    image: mysql:8.4
    platform: linux/arm64/v8
    container_name: laravel-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: development
      TZ: 'Asia/Tokyo'
    networks:
      - dev_network

  mail:
    image: axllent/mailpit:latest
    container_name: laravel-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit-data:/data
    environment:
      TZ: Asia/Tokyo
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - dev_network

volumes:
  mysql_data:
  vendor:
  mailpit-data:

networks:
  dev_network:
    name: dev_network
    external: true
